// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sdk.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 排序方向
type SortDirection int32

const (
	SortDirection_Asc  SortDirection = 0
	SortDirection_Desc SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "Asc",
	1: "Desc",
}

var SortDirection_value = map[string]int32{
	"Asc":  0,
	"Desc": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}

func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}

type DaprModuleKind int32

const (
	DaprModuleKind_DaprModuleKindUnknown    DaprModuleKind = 0
	DaprModuleKind_DaprModuleKindInvocation DaprModuleKind = 1
	DaprModuleKind_DaprModuleKindEvent      DaprModuleKind = 2
	DaprModuleKind_DaprModuleKindDelayEvent DaprModuleKind = 3
	DaprModuleKind_DaprModuleKindHealth     DaprModuleKind = 4
)

var DaprModuleKind_name = map[int32]string{
	0: "DaprModuleKindUnknown",
	1: "DaprModuleKindInvocation",
	2: "DaprModuleKindEvent",
	3: "DaprModuleKindDelayEvent",
	4: "DaprModuleKindHealth",
}

var DaprModuleKind_value = map[string]int32{
	"DaprModuleKindUnknown":    0,
	"DaprModuleKindInvocation": 1,
	"DaprModuleKindEvent":      2,
	"DaprModuleKindDelayEvent": 3,
	"DaprModuleKindHealth":     4,
}

func (x DaprModuleKind) String() string {
	return proto.EnumName(DaprModuleKind_name, int32(x))
}

func (DaprModuleKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{1}
}

// 按limit分页
type ListParam struct {
	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (m *ListParam) Reset()         { *m = ListParam{} }
func (m *ListParam) String() string { return proto.CompactTextString(m) }
func (*ListParam) ProtoMessage()    {}
func (*ListParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}
func (m *ListParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParam.Merge(m, src)
}
func (m *ListParam) XXX_Size() int {
	return m.Size()
}
func (m *ListParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParam.DiscardUnknown(m)
}

var xxx_messageInfo_ListParam proto.InternalMessageInfo

func (m *ListParam) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListParam) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type DaprHandler struct {
	ModuleKind  DaprModuleKind    `protobuf:"varint,1,opt,name=moduleKind,proto3,enum=hdget.protobuf.DaprModuleKind" json:"moduleKind,omitempty"`
	PkgPath     string            `protobuf:"bytes,2,opt,name=pkgPath,proto3" json:"pkgPath,omitempty"`
	Module      string            `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Name        string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Alias       string            `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Comments    []string          `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (m *DaprHandler) Reset()         { *m = DaprHandler{} }
func (m *DaprHandler) String() string { return proto.CompactTextString(m) }
func (*DaprHandler) ProtoMessage()    {}
func (*DaprHandler) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{1}
}
func (m *DaprHandler) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DaprHandler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DaprHandler.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DaprHandler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaprHandler.Merge(m, src)
}
func (m *DaprHandler) XXX_Size() int {
	return m.Size()
}
func (m *DaprHandler) XXX_DiscardUnknown() {
	xxx_messageInfo_DaprHandler.DiscardUnknown(m)
}

var xxx_messageInfo_DaprHandler proto.InternalMessageInfo

func (m *DaprHandler) GetModuleKind() DaprModuleKind {
	if m != nil {
		return m.ModuleKind
	}
	return DaprModuleKind_DaprModuleKindUnknown
}

func (m *DaprHandler) GetPkgPath() string {
	if m != nil {
		return m.PkgPath
	}
	return ""
}

func (m *DaprHandler) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *DaprHandler) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DaprHandler) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *DaprHandler) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *DaprHandler) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterEnum("hdget.protobuf.SortDirection", SortDirection_name, SortDirection_value)
	proto.RegisterEnum("hdget.protobuf.DaprModuleKind", DaprModuleKind_name, DaprModuleKind_value)
	proto.RegisterType((*ListParam)(nil), "hdget.protobuf.ListParam")
	proto.RegisterType((*DaprHandler)(nil), "hdget.protobuf.DaprHandler")
	proto.RegisterMapType((map[string]string)(nil), "hdget.protobuf.DaprHandler.AnnotationsEntry")
}

func init() { proto.RegisterFile("sdk.proto", fileDescriptor_70decb0fb6f436df) }

var fileDescriptor_70decb0fb6f436df = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xd5, 0x5a, 0x8e, 0x1d, 0x8d, 0xa9, 0x59, 0xa6, 0x69, 0xbb, 0x0d, 0x45, 0x18, 0x9f, 0x4c,
	0x28, 0x32, 0xa4, 0x97, 0x92, 0x42, 0x20, 0xc5, 0x81, 0x94, 0x7e, 0x10, 0x14, 0x7a, 0xe9, 0x6d,
	0x2d, 0x6d, 0x6d, 0x61, 0x69, 0x57, 0x48, 0x2b, 0x17, 0xf7, 0x57, 0xf4, 0xdc, 0x5f, 0xd4, 0x63,
	0x2e, 0x85, 0x1e, 0x8b, 0xfd, 0x47, 0xca, 0xae, 0x1c, 0xd7, 0x6a, 0x73, 0xd2, 0xbc, 0x79, 0xf3,
	0x66, 0xdf, 0x3c, 0x81, 0x57, 0xc6, 0x8b, 0x20, 0x2f, 0x94, 0x56, 0xd8, 0x9f, 0xc7, 0x33, 0xa1,
	0x6b, 0x30, 0xad, 0x3e, 0x0f, 0x5f, 0x81, 0xf7, 0x2e, 0x29, 0xf5, 0x35, 0x2f, 0x78, 0x86, 0x08,
	0xed, 0x9c, 0xcf, 0x04, 0x23, 0x03, 0x32, 0x72, 0x43, 0x5b, 0xe3, 0x31, 0x1c, 0x9a, 0xef, 0x4d,
	0xf2, 0x55, 0xb0, 0x96, 0xed, 0xef, 0xf0, 0xf0, 0x67, 0x0b, 0x7a, 0x13, 0x9e, 0x17, 0x57, 0x5c,
	0xc6, 0xa9, 0x28, 0xf0, 0x1c, 0x20, 0x53, 0x71, 0x95, 0x8a, 0xb7, 0x89, 0x8c, 0xed, 0x96, 0xfe,
	0xa9, 0x1f, 0x34, 0x5f, 0x0c, 0x8c, 0xe0, 0xfd, 0x6e, 0x2a, 0xdc, 0x53, 0x20, 0x83, 0x6e, 0xbe,
	0x98, 0x5d, 0x73, 0x3d, 0xb7, 0x4f, 0x79, 0xe1, 0x1d, 0xc4, 0xc7, 0xd0, 0xa9, 0xe7, 0x98, 0x6b,
	0x89, 0x2d, 0x32, 0x8e, 0x25, 0xcf, 0x04, 0x6b, 0xdb, 0xae, 0xad, 0xf1, 0x08, 0x0e, 0x78, 0x9a,
	0xf0, 0x92, 0x1d, 0xd8, 0x66, 0x0d, 0xf0, 0x03, 0xf4, 0xb8, 0x94, 0x4a, 0x73, 0x9d, 0x28, 0x59,
	0xb2, 0xee, 0xc0, 0x1d, 0xf5, 0x4e, 0x9f, 0xdf, 0x67, 0x6e, 0x7b, 0x4d, 0x70, 0xf1, 0x77, 0xfc,
	0x52, 0xea, 0x62, 0x15, 0xee, 0x2f, 0x30, 0xb9, 0x44, 0x2a, 0xcb, 0x84, 0xd4, 0x25, 0xeb, 0x0c,
	0xdc, 0x91, 0x17, 0xee, 0xf0, 0xf1, 0x39, 0xd0, 0x7f, 0xc5, 0x48, 0xc1, 0x5d, 0x88, 0x95, 0x0d,
	0xc5, 0x0b, 0x4d, 0x69, 0x7c, 0x2e, 0x79, 0x5a, 0x89, 0xed, 0xad, 0x35, 0x38, 0x6b, 0xbd, 0x24,
	0x27, 0x43, 0x78, 0x70, 0xa3, 0x0a, 0x3d, 0x49, 0x0a, 0x11, 0x99, 0x15, 0xd8, 0x05, 0xf7, 0xa2,
	0x8c, 0xa8, 0x83, 0x87, 0xd0, 0x9e, 0x88, 0x32, 0xa2, 0xe4, 0xe4, 0x3b, 0x81, 0x7e, 0x33, 0x4a,
	0x7c, 0x0a, 0x8f, 0x9a, 0x9d, 0x8f, 0x72, 0x21, 0xd5, 0x17, 0x49, 0x1d, 0x7c, 0x06, 0xac, 0x49,
	0xbd, 0x91, 0x4b, 0x15, 0x59, 0x7f, 0x94, 0xe0, 0x13, 0x78, 0xd8, 0x64, 0x2f, 0x97, 0x42, 0x6a,
	0xda, 0xfa, 0x5f, 0x36, 0x11, 0x29, 0x5f, 0xd5, 0xac, 0x8b, 0x0c, 0x8e, 0x9a, 0xec, 0x95, 0xe0,
	0xa9, 0x9e, 0xd3, 0xf6, 0xeb, 0xb3, 0x1f, 0x6b, 0x9f, 0xdc, 0xae, 0x7d, 0xf2, 0x7b, 0xed, 0x93,
	0x6f, 0x1b, 0xdf, 0xb9, 0xdd, 0xf8, 0xce, 0xaf, 0x8d, 0xef, 0x7c, 0x1a, 0xcc, 0x12, 0x3d, 0xaf,
	0xa6, 0x41, 0xa4, 0xb2, 0xb1, 0xcd, 0x7e, 0x6c, 0x52, 0x53, 0x72, 0x7c, 0xf7, 0x0b, 0xa6, 0x1d,
	0x5b, 0xbd, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x61, 0x18, 0x63, 0xea, 0xb5, 0x02, 0x00, 0x00,
}

func (m *ListParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PageSize != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DaprHandler) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DaprHandler) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DaprHandler) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Annotations) > 0 {
		for k := range m.Annotations {
			v := m.Annotations[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintSdk(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintSdk(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintSdk(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Comments) > 0 {
		for iNdEx := len(m.Comments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Comments[iNdEx])
			copy(dAtA[i:], m.Comments[iNdEx])
			i = encodeVarintSdk(dAtA, i, uint64(len(m.Comments[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Alias) > 0 {
		i -= len(m.Alias)
		copy(dAtA[i:], m.Alias)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Alias)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PkgPath) > 0 {
		i -= len(m.PkgPath)
		copy(dAtA[i:], m.PkgPath)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.PkgPath)))
		i--
		dAtA[i] = 0x12
	}
	if m.ModuleKind != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.ModuleKind))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSdk(dAtA []byte, offset int, v uint64) int {
	offset -= sovSdk(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovSdk(uint64(m.Page))
	}
	if m.PageSize != 0 {
		n += 1 + sovSdk(uint64(m.PageSize))
	}
	return n
}

func (m *DaprHandler) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ModuleKind != 0 {
		n += 1 + sovSdk(uint64(m.ModuleKind))
	}
	l = len(m.PkgPath)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Alias)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	if len(m.Comments) > 0 {
		for _, s := range m.Comments {
			l = len(s)
			n += 1 + l + sovSdk(uint64(l))
		}
	}
	if len(m.Annotations) > 0 {
		for k, v := range m.Annotations {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovSdk(uint64(len(k))) + 1 + len(v) + sovSdk(uint64(len(v)))
			n += mapEntrySize + 1 + sovSdk(uint64(mapEntrySize))
		}
	}
	return n
}

func sovSdk(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSdk(x uint64) (n int) {
	return sovSdk(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSdk(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSdk
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DaprHandler) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DaprHandler: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DaprHandler: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleKind", wireType)
			}
			m.ModuleKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModuleKind |= DaprModuleKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PkgPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PkgPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = append(m.Comments, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Annotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Annotations == nil {
				m.Annotations = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSdk
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSdk
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSdk
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthSdk
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSdk
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthSdk
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthSdk
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSdk(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthSdk
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Annotations[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdk(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSdk
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSdk(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSdk
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSdk
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSdk
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSdk        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSdk          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSdk = fmt.Errorf("proto: unexpected end of group")
)
